name: einventorycomputer
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7 # or latest version
  firebase_core: ^2.27.0 # or latest version
  cloud_firestore: ^4.15.0
  firebase_auth: ^4.17.0
  provider: ^6.1.5
  flutter_spinkit: ^5.2.1
  fl_chart: ^0.68.0
  firebase_storage: ^11.6.0  # Add this
  image_picker: ^1.0.4       # Add this

  # PDF generation dependencies
  pdf: ^3.10.7
  printing: ^5.11.1
  path_provider: ^2.1.1
  intl: ^0.19.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: PoetsenOne
      fonts:
        - asset: assets/fonts/PoetsenOne-Regular.ttf
    - family: SansRegular
      fonts:
      - asset: assets/fonts/SourceSans3-VariableFont_wght.ttf


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/eInventory.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/eInventory.png"

